# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordPlugin
                                 A QGIS plugin
 создание таблицы координат
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-13
        copyright            : (C) 2022 by Платон Чекмазов
        email                : chekmazovp@icloud.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import sys
import os
import sys
import subprocess
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordPlugin class from file CoordPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    try:
        import sys
        import os
        this_dir = os.path.dirname(os.path.realpath(__file__))
        path = os.path.join(this_dir, 'openpyxl-3.0.10-py2.py3-none-any.whl')
        sys.path.append(path)
        import openpyxl
    except:
        pass

    from .Coord_plugin import CoordPlugin
    return CoordPlugin(iface)
